# Generated by Django 4.2.7 on 2023-12-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexp',
            name='Image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
