# Generated by Django 4.2.7 on 2023-12-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demo', '0004_newsp'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Number', models.TextField()),
                ('Message', models.TextField()),
            ],
        ),
    ]
