# Generated by Django 4.2.7 on 2023-12-26 11:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Demo', '0006_cyclep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutp',
            name='Description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='cyclep',
            name='Description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='indexp',
            name='Description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='newsp',
            name='Description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
